### ISSUE TITLE
Xcode 8.3.2 Build success, but plugin non-functional, popup allowing Xvim not shown

### ISSUE THREAD

**Issue by truongngoclinh** [XVimProject/XVim#1063]
# Description
I can install Xvim successfully by using develop branch, but no VIM feature in Xcode when I open projects. I cant see the notice for: "allow xcode load Xvim from bundles".

# Operation
 ~/XVim  ➦ fa5224b  sudo make
xcodebuild -configuration Release
2017-04-21 21:00:23.704 xcodebuild[19159:92286] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin' not present in DVTPlugInCompatibilityUUIDs
=== BUILD TARGET XVim OF PROJECT XVim WITH CONFIGURATION Release ==
....
** BUILD SUCCEEDED **

# Expected behaviour
XVim working in Xcode. At least show the popup that allows load Xvim.

# Environments
  - Xcode Version [ 8.3.2 ]
  - XVim branch and revision [ develop / fa5224b ]
  - Keyboard Language [ English US ]
  - Input source language [ English US ]

# Crash log (if any)
   
     [ Paste the log here ]

**Comment by tidbeck** [comment]
Have you followed the [Install XVim for Xcode 8](https://github.com/XVimProject/XVim/blob/master/INSTALL_Xcode8.md) instructions (re-signed Xcode)?

**Comment by truongngoclinh** [comment]
@tidbeck, sure I signed succesfully:  sudo codesign -f -s XcodeSigner /Applications/Xcode.app

**Comment by truongngoclinh** [comment]
oh sorry I found that I **didnot select "login" in the left pane **, let me redo.

**Comment by truongngoclinh** [comment]
Build failed if I use master branch.
``The following build commands failed:
	Ld build/Release/XVim.xcplugin/Contents/MacOS/XVim normal x86_64``

**Comment by windniw** [comment]
Build success and work well in Xcode 8.3.1
- Xvim branch     develop
- Xcode version  8.3.1

**Comment by gonefish** [comment]
me too

**Comment by podkovyrin** [comment]
Try to update compatibility UUIDs with the following command and restart Xcode:
```
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`
```

**Comment by hyouuu** [comment]
Followed @podkovyrin's command, re-signed Xcode and re-make works for me on 8.3.2

**Comment by rqueue** [comment]
Has anyone else found another solution? I can't seem to get it to work using the command from podkovyrin

**Comment by matachi** [comment]
@rqueue Not sure what command did the trick, but I ran the following commands a couple of times:

```
$ defaults delete  com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-8.3.2
$ find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`
$ sudo codesign -f -s XcodeSigner /Applications/Xcode.app
$ make
```

Eventually XVim started to work in Xcode again. I'm also running Xcode 8.3.2 and I'm on the develop branch of XVim.

**Comment by hanl001** [comment]
you should create an other sign and Re-signing Xcode again

**Comment by truongngoclinh** [comment]
It now works well on Xcode 8.3.2 with develop branch. Thank you all for your reply!

**Comment by rqueue** [comment]
What did it in the end for me was opening the xvime project in xcode and building it there + all the other steps people mentioned

**Comment by bduhbya** [comment]
To clarify, if we want the latest plugin code, we need to use "develop" branch and NOT master?  Master fails to build for me (Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_IDEPlaygroundEditor", referenced from:
      anon in IDEPlaygroundEditor+XVim.o
      l_OBJC_$_CATEGORY_IDEPlaygroundEditor_$_XVim in IDEPlaygroundEditor+XVim.o
      objc-class-ref in XVimHookManager.o
ld: symbol(s) not found for architecture x86_64)

But, https://github.com/pebble8888/XVim.git works.  I had no trouble with the codesign part.

**Comment by WellerQu** [comment]
I have the same problem, but my xcode version is 8.3.3. Any ideas, please.

**Comment by rqueue** [comment]
@wellerqu have you tried opening the xvim project itself in Xcode and running it in addition to all the other steps people mentioned?

**Comment by hidez** [comment]
@WellerQu Have you tried develop branch of XVim? Master branch failed with make. But develop branch works for me on Xcode8.3.3.

**Comment by WellerQu** [comment]
@rqueue Yes, I have tried all the other steps in this issue. But can't get the expected result. And I get some warns: 
<img width="262" alt="screen shot 2017-06-12 at 14 30 13" src="https://user-images.githubusercontent.com/3367607/27021544-c5cf9468-4f7b-11e7-8e01-a31e118e1b4a.png">

**Comment by WellerQu** [comment]
@hidez Yeah, I have tried develop branch. 
<img width="1440" alt="screen shot 2017-06-12 at 14 27 30" src="https://user-images.githubusercontent.com/3367607/27021650-677a6298-4f7c-11e7-8787-10fa20d9d662.png">

**Comment by WellerQu** [comment]
Thanks all. And I resolve it with @bduhbya 's solution.
