### PR TITLE
Add Xcode 8.3beta1 compatibility

### PR DESCRIPTION
**Pull request by mkalinowski**
**Problem:**
Compilation of the lastest `master` on Xcode 8.3beta1 fails with:
```
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -bundle -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -L/Users/mikolaj/Projects/XVim/build/Release -L/Applications/Xcode-beta.app/Contents/Developer/../PlugIns/IDESourceEditor.ideplugin/Contents/MacOS -F/Users/mikolaj/Projects/XVim/build/Release -F/Applications/Xcode-beta.app/Contents/Developer/../Frameworks -F/Applications/Xcode-beta.app/Contents/Developer/../PlugIns -F/Applications/Xcode-beta.app/Contents/Developer/../SharedFrameworks -filelist /Users/mikolaj/Projects/XVim/build/XVim.build/Release/XVim.build/Objects-normal/x86_64/XVim.LinkFileList -mmacosx-version-min=10.7 -Xlinker
-object_path_lto -Xlinker /Users/mikolaj/Projects/XVim/build/XVim.build/Release/XVim.build/Objects-normal/x86_64/XVim_lto.o -fobjc-arc -fobjc-link-runtime
-framework AppKit -framework Cocoa -framework IDEFoundation -framework IDEKit -framework DVTFoundation -framework DVTKit /Applications/Xcode-beta.app/Contents/PlugIns/IDELanguageSupportUI.ideplugin/Contents/MacOS/IDELanguageSupportUI /Applications/Xcode-beta.app/Contents/PlugIns/IDESourceEditor.ideplugin/Contents/MacOS/IDESourceEditor -Xlinker -dependency_info -Xlinker /Users/mikolaj/Projects/XVim/build/XVim.build/Release/XVim.build/Objects-normal/x86_64/XVim_dependency_info.dat -o /Users/mikolaj/Projects/XVim/build/Release/XVim.xcplugin/Contents/MacOS/XVim
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_IDEPlaygroundEditor", referenced from:
      objc-class-ref in XVimHookManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

```

**Root cause:**
The problem happens, because `IDEPlaygroundEditor` is not defined anymore in `
/Applications/Xcode.app/Contents/PlugIns/IDELanguageSupportUI.ideplugin/Contents/MacOS/IDELanguageSupportUI`

**Solution:**
Remove `IDEPlaygroundEditor+XVim` extension and rely on `IDESourceCodeEdtior+XVim`

**Testing:**
XVim still works in Playgrounds in Xcode8.3beta1

### CODE REVIEW

**Comment by fe9lix** [comment]
Hi! Still couldn't compile XVim with the changes of your PR. I had to go into the project and remove the import from XVimHookManager.m and also remove IDEPlaygroundEditor+XVim.m from Compile Sources (Target -> Build Phases...).

**Comment by tmm1** [comment]
@fe9lix Can you open a PR with your fix?

**Comment by keith** [comment]
Here's a new PR that makes all these changes https://github.com/XVimProject/XVim/pull/1055

**Comment by darylsew** [comment]
Hm, I'm getting this error in XCode 8.3.1 (not Beta), and it looks very similar. Any thoughts?

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_IDEPlaygroundEditor", referenced from:
      anon in IDEPlaygroundEditor+XVim.o
      l_OBJC_$_CATEGORY_IDEPlaygroundEditor_$_XVim in IDEPlaygroundEditor+XVim.o
      objc-class-ref in XVimHookManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by darylsew** [comment]
This was on master (revision 4ac27255), it actually builds fine on develop and everything seems to work, so you can ignore my earlier comment.
