### ISSUE TITLE
Does not build on macOS 10.15.3 / Xcode 11.3.1

### ISSUE THREAD

**Issue by roselma** [XVimProject/XVim#1105]
# Operation
```
git clone git clone https://github.com/XVimProject/XVim.git
cd XVim
make
```

# Environments
  - Xcode Version: 11.3.1
  - XVim branch and revision: master, 53c652421ca8ad63a2380a5cad316b1997999b8a
  - Keyboard Language: en-us
  - Input source language: en-us

# Crash log (if any)
Build output has been trimmed to include only errors and warnings.  Complete log attached.

[xvim-build-fail.txt](https://github.com/XVimProject/XVim/files/4157024/xvim-build-fail.txt)

```   
xcodebuild -configuration Release 

...

/Users/m/XVim/XVim/Logger.m:164:20: warning: unused variable 'e' [-Wunused-variable]
    for( NSString* e in [ex callStackSymbols]){
                   ^
1 warning generated.

...

/Users/m/XVim/XVim/DVTSourceTextView+XVim.m:34:17: warning: method definition for
      '_drawInsertionPointInRect:color:' not found [-Wincomplete-implementation]
@implementation DVTSourceTextView(XVim)
                ^
In file included from /Users/m/XVim/XVim/DVTSourceTextView+XVim.m:20:
XVim/DVTSourceTextView+XVim.h:48:1: note: method '_drawInsertionPointInRect:color:' declared here
- (void)_drawInsertionPointInRect:(NSRect)rect color:(NSColor*)color;
^

...

In file included from /Users/m/XVim/XVim/DVTTextSidebarView+XVim.m:10:
XVim/DVTTextSidebarView+XVim.h:11:9: fatal error: 'DVTTextSidebarView.h' file not found
#import "DVTTextSidebarView.h"
        ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.

...

In file included from /Users/m/XVim/XVim/XVimHookManager.m:11:
XVim/DVTTextSidebarView+XVim.h:11:9: fatal error: 'DVTTextSidebarView.h' file not found
#import "DVTTextSidebarView.h"
        ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.

...

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/m/XVim/build/XVim.build/Release/XVim.build/Objects-normal/x86_64/DVTTextSidebarView+XVim.o /Users/m/XVim/XVim/DVTTextSidebarView+XVim.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/m/XVim/build/XVim.build/Release/XVim.build/Objects-normal/x86_64/XVimHookManager.o /Users/m/XVim/XVim/XVimHookManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
```

**Comment by roselma** [comment]
[xvim-build-fail.txt](https://github.com/XVimProject/XVim/files/4157024/xvim-build-fail.txt)

**Comment by lando2319** [comment]
Try the XVim2 for xcode 9 and greater. https://github.com/XVimProject/XVim2
