### ISSUE TITLE
Build failure using Xcode 8.3 beta 3

### ISSUE THREAD

**Issue by kconner** [XVimProject/XVim#1050]
# Operation

After self-signing Xcode:

```
sudo xcode-select -s <path-to-xcode-8.3-beta-3>
make
```

# Expected behaviour

Should build XVim and install it to Xcode's plugins.

# Environments

  - Xcode Version: 8.3 beta 3, 8W132P
  - XVim branch and revision: Current develop branch, ec2c601
  - Keyboard Language: US English Dvorak
  - Input source language: US English Dvorak

# Crash log (if any)

… (long build log) …

Ld build/Release/XVim.xcplugin/Contents/MacOS/XVim normal x86_64
    cd /Users/kevinconner/src/XVimProject/XVim
    export MACOSX_DEPLOYMENT_TARGET=10.7
    /Applications/Xcode-beta\ with\ XVim.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -bundle -isysroot /Applications/Xcode-beta\ with\ XVim.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -L/Users/kevinconner/src/XVimProject/XVim/build/Release -L/Applications/Xcode-beta\ with\ XVim.app/Contents/Developer/../PlugIns/IDESourceEditor.ideplugin/Contents/MacOS -F/Users/kevinconner/src/XVimProject/XVim/build/Release -F/Applications/Xcode-beta\ with\ XVim.app/Contents/Developer/../Frameworks -F/Applications/Xcode-beta\ with\ XVim.app/Contents/Developer/../PlugIns -F/Applications/Xcode-beta\ with\ XVim.app/Contents/Developer/../SharedFrameworks -filelist /Users/kevinconner/src/XVimProject/XVim/build/XVim.build/Release/XVim.build/Objects-normal/x86_64/XVim.LinkFileList -mmacosx-version-min=10.7 -Xlinker -object_path_lto -Xlinker /Users/kevinconner/src/XVimProject/XVim/build/XVim.build/Release/XVim.build/Objects-normal/x86_64/XVim_lto.o -fobjc-arc -fobjc-link-runtime -framework AppKit -framework Cocoa -framework IDEFoundation -framework IDEKit -framework DVTFoundation -framework DVTKit /Applications/Xcode-beta\ with\ XVim.app/Contents/PlugIns/IDELanguageSupportUI.ideplugin/Contents/MacOS/IDELanguageSupportUI /Applications/Xcode-beta\ with\ XVim.app/Contents/PlugIns/IDESourceEditor.ideplugin/Contents/MacOS/IDESourceEditor -Xlinker -dependency_info -Xlinker /Users/kevinconner/src/XVimProject/XVim/build/XVim.build/Release/XVim.build/Objects-normal/x86_64/XVim_dependency_info.dat -o /Users/kevinconner/src/XVimProject/XVim/build/Release/XVim.xcplugin/Contents/MacOS/XVim
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_IDEPlaygroundEditor", referenced from:
      anon in IDEPlaygroundEditor+XVim.o
      l_OBJC_$_CATEGORY_IDEPlaygroundEditor_$_XVim in IDEPlaygroundEditor+XVim.o
      objc-class-ref in XVimHookManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kconner** [comment]
Building @pebble8888's commit solves the problem.

**Comment by mna** [comment]
Same for me (I ported the changes on XVim's `master` because the fork had a few more diffs, and it worked). Nice workaround until the changes are merged.

**Comment by Menq** [comment]
@pebble8888 done a great job ! thanks

**Comment by keith** [comment]
https://github.com/XVimProject/XVim/pull/1055 This PR has Xcode 8.3 compatibility

**Comment by pbrewczynski** [comment]
OK. But who have the privileges to merge it to this repository?

**Comment by JugglerShu** [comment]
Sorry but I don't have much time to merge it to master branch. The fix is already merged into develop branch.

**Comment by CallumHoward** [comment]
Got it working with Xcode 8.3 using the above, but now in Xcode 8.3.1, even though it builds, it doesn't seem to load XVim.

**Comment by keithZumper** [comment]
Builds but doesn't load in 8.3

**Comment by JugglerShu** [comment]
Did you guys re-sign the new Xcode??

**Comment by CallumHoward** [comment]
@JugglerShu Ah yes, resigning fixed it. Now XVim is working using `xcode-8.3-release` branch on Xcode 8.3.1. Thanks!

**Comment by jduan** [comment]
I'm on the latest master branch (4ac2725) and "make" fails for my xcode (8.3.1). Can anyone help?

```
Ld build/Release/XVim.xcplugin/Contents/MacOS/XVim normal x86_64
    cd /Users/jduan/github/XVim
    export MACOSX_DEPLOYMENT_TARGET=10.7
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -bundle -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -L/Users/jduan/github/XVim/build/Release -L/Applications/Xcode.app/Contents/Developer/../PlugIns/IDESourceEditor.ideplugin/Contents/MacOS -F/Users/jduan/github/XVim/build/Release -F/Applications/Xcode.app/Contents/Developer/../Frameworks -F/Applications/Xcode.app/Contents/Developer/../PlugIns -F/Applications/Xcode.app/Contents/Developer/../SharedFrameworks -filelist /Users/jduan/github/XVim/build/XVim.build/Release/XVim.build/Objects-normal/x86_64/XVim.LinkFileList -mmacosx-version-min=10.7 -Xlinker -object_path_lto -Xlinker /Users/jduan/github/XVim/build/XVim.build/Release/XVim.build/Objects-normal/x86_64/XVim_lto.o -fobjc-arc -fobjc-link-runtime -framework AppKit -framework Cocoa -framework IDEFoundation -framework IDEKit -framework DVTFoundation -framework DVTKit /Applications/Xcode.app/Contents/PlugIns/IDELanguageSupportUI.ideplugin/Contents/MacOS/IDELanguageSupportUI /Applications/Xcode.app/Contents/PlugIns/IDESourceEditor.ideplugin/Contents/MacOS/IDESourceEditor -Xlinker -dependency_info -Xlinker /Users/jduan/github/XVim/build/XVim.build/Release/XVim.build/Objects-normal/x86_64/XVim_dependency_info.dat -o /Users/jduan/github/XVim/build/Release/XVim.xcplugin/Contents/MacOS/XVim
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_IDEPlaygroundEditor", referenced from:
      anon in IDEPlaygroundEditor+XVim.o
      l_OBJC_$_CATEGORY_IDEPlaygroundEditor_$_XVim in IDEPlaygroundEditor+XVim.o
      objc-class-ref in XVimHookManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
        Ld build/Release/XVim.xcplugin/Contents/MacOS/XVim normal x86_64
(1 failure)
make: *** [release] Error 65
```

**Comment by tidbeck** [comment]
@jduan you need to build the `develop` branch to get support for Xcode 8.3.1 as `IDEPlaygroundEditor` has been removed. See #1055

**Comment by jduan** [comment]
@tidbeck thank you so much! I built the develop branch and it worked beautifully.

**Comment by dgutyanghs** [comment]
Also work in XCode8.3.2 , good job!

**Comment by cor** [comment]
@tidbeck Thanks a lot! Switching to the `develop` branch made it work in Xcode 8.3.2 for me.

**Comment by snapchatdotcom** [comment]
how do you guys switch to a develop branch?

**Comment by jduan** [comment]
It's standard git operations:

* git fetch origin
* git checkout origin/develop

**Comment by 13hoop** [comment]
thx

worked!

**Comment by Chan-Chun** [comment]
1.use Xcode to open xVim project!
2.entry "/XVim/Event Dispatchers" and then delete  "IDEPlaygroundEditor+Xvim.h” and “IDEPlaygroundEditor+Xvim.m"  
3.and entry "XVimHookManager.m" to delete the reference of them .

it works!

**Comment by BBHNation** [comment]
As @Chan-Chun said, it works on 8.3.3
