### ISSUE TITLE
develop failing to build on Xcode 6.1

### ISSUE THREAD

**Issue by neybis** [XVimProject/XVim#854]
OS X 10.10.5
Xcode 6.1

This commit (125c207a73d9f7584d52c2b6bd217f17ef327e20) seems to have broken the branch.
```
/Volumes/git/XVim_temp/XVim/IDESourceCodeEditor+XVim.m:32:37: error: no visible @interface for 'NSView' declares the selector 'contentView'
    NSView* container = [[obj view] contentView];
                         ~~~~~~~~~~ ^~~~~~~~~~~
1 error generated.
```

**Comment by neybis** [comment]
Works with Xcode 6.4.

Do we care about this level of backward compatibility??

**Comment by pebble8888** [comment]
I have enough time to discuss.
Try these sample that is very rough.
```
    id obj = [self xvim_initWithNibName:name bundle:bundle document:doc];
    id v = [obj view];
    NSView* container;
    DEBUG_LOG(@"v [%@]", v);
    if ([NSStringFromClass([v class]) isEqualToString:@"DVTControllerContentView"]) {
        // Xcode7 or Xcode6.4??? 
        container = [v contentView];
    } else {
        // Xcode6.1 ???
        // container is IDESourceCodeEditorContainerView
        container = [obj containerView];
    }
    DEBUG_LOG("container [%@]", container);
    
```

**Comment by neybis** [comment]
Let me fall back to 6.1.1 and I'll re-test to see if we can get this resolved. Thanks so much for helping out :) I really think I will be using this plug-in a lot over the next few years and hope I can learn enough about it to contribute back whenever I can ;)

**Comment by neybis** [comment]
Working like a charm! :) Ran it through lldb and I'm no longer getting nil (my fix was WAYYY off lol). I'll submit a pull request soon with a few others so this can be resolved ;)

**Comment by neybis** [comment]
Submitted pull request #855

**Comment by JugglerShu** [comment]
I fixed it.
This is no the runtime error but compile time error. The `contentView` exists in both versions.
I don't know the detail but it seems after Xcode 6.4, compiler doesn't make error for undeclared method call (maybe because it is declared in its one of child class).
I just replace the call with `performSelector`.

**Comment by JugglerShu** [comment]
@neybis Please check if this works. If it works correctly I'll close your PR.

**Comment by neybis** [comment]
Worked like a charm. Thanks @JugglerShu!
